### ISSUE TITLE
Bad

### ISSUE THREAD

**Issue by Madji** [openspace42/aenigma#15]
aenigma/aenigma/installer-v0.4: line 670: dig: command not found

and requests of utilities which may or may not be on the server, but they are not put together with fail2ban, ufw, and other

**Comment by nordurljosahvida** [comment]
@Madji Hi there! Thanks for trying aenigma out.
I've just published v0.42, give it a try, it has tons of cool new stuff ;]
All utilities you mentioned [except for dig] are installed in [DFBS](https://github.com/nikksno/Debian-First-Boot-Setup/), which is a requirement for the installation of aenigma.
I'm fixing the dig problem right now.
Thanks for the help!

**Comment by nordurljosahvida** [comment]
@Madji I've just added the dependency install for dig [dnsutils] and ufw [in case the user skipped installation in the DFBS]. Let me know if it works for you and your OS and version! ;]
