### ISSUE TITLE
unbound variable - SSH_CLIENT

### ISSUE THREAD

**Issue by spoctoss** [openspace42/aenigma#29]
Not sure if I'm just doing something wrong but can't seem to get this working.

Initiating installer...

./aenigma/install.sh: line 53: SSH_CLIENT: unbound variable

**Comment by mcat-ee** [comment]
Although this isn't a great solution, I executed a deployment by removing the IF/ELSE block starting on line 53.

**Comment by nordurljosahvida** [comment]
Hi! Sorry for the late reply! Are you running ubuntu 16? Are you using screen? Any other relevant things to know?

**Comment by nordurljosahvida** [comment]
@kylesmith63 @mcat-ee I just published a fix. If you have three minutes, please try it out and let me know if it works! [aenigma is 100% idempotent, you can run the installer as many times as you like and it will cause no harm at all ;]
Thanks for your help!

**Comment by nordurljosahvida** [comment]
Closing for now. Let me know if you still need any help.

**Comment by spoctoss** [comment]
@nikksno sorry for late response I'll give it a shot and let you know

**Comment by nordurljosahvida** [comment]
@kylesmith63 no problem, thank you.

**Comment by spoctoss** [comment]
@nikksno all working now thanks

**Comment by nordurljosahvida** [comment]
@kylesmith63 very good, please remember to send some feedback if you can! ;]
