### ISSUE TITLE
Website is down

### ISSUE THREAD

**Issue by lukateras** [openspace42/aenigma#34]
http://aenigma.xyz leads to a Nginx setup page, https://aenigma.xyz leads to Mastodon instance.

**Comment by nordurljosahvida** [comment]
@yegortimoshenko Very true, it's probably time I setup a landing page for the project, I've spent sleepless nights working on clusterization and now that that's complete I can focus on these sort of things. If you have any other tips and feedback please send them my way!

**Comment by nordurljosahvida** [comment]
@yegortimoshenko working on this ;]

**Comment by nordurljosahvida** [comment]
@yegortimoshenko project is shutdown, just in case it's still listed on prism-break. I highly recommend matrix/element for everyone!
