### ISSUE TITLE
Enforce end-to-end encryption

### ISSUE THREAD

**Issue by lukateras** [openspace42/aenigma#35]
It would be great if this were to enforce end-to-end encryption (or at least, provide it as an install-time option). Most users are going to deploy XMPP servers to untrusted hardware, and unfortunately most clients default to and allow unencrypted messages.

**Comment by nordurljosahvida** [comment]
@yegortimoshenko Thank you so much for the pull in prism-break, thrilled to be there.

I know about an option to *dis*able automatic OMEMO in conversations, but the new version of such client already defaults to OMEMO whenever the other end also supports it.

Other clients have massive issues with OMEMO, chatsecure on iOS is extremely restrictive on new key appearances and hardly ever works with conversations on the first try in my experience, so forcing OMEMO on by default [if at all possible server-side] would probably not be a great idea, no?

Not sure about other clients, I've been closely following updates on dino, but its implementation of OMEMO is still partial.

What do you think and what have I missed?

Thanks again!

**Comment by moppman** [comment]
On Prosody, there is a community module called "mod_e2e_policy" (https://modules.prosody.im).
Maybe there is something similar for ejabberd?

**Comment by nordurljosahvida** [comment]
If ejabberd had an updated and complete documentation, we could probably know.

However, keep in mind that to my knowledge if a client doesn't automatically enable omemo it is [probably not a good idea to force it](https://gultsch.de/omemo_by_default.html)

I can confirm that the only client I've had a reliable experience on with omemo is conversations, chatsecure is really fiddly and dino for Linux is super beta for now. What other clients are you thinking about?

**Comment by moppman** [comment]
converse.js (with libsignal) works pretty well.

**Comment by nordurljosahvida** [comment]
Very cool I had never tried it out thanks!

I've read the module specs and I understand why it's important, but also as I've learned from Holger Weiß you really don't want to be cutting bridges with older clients, I agree with that.

Anyway, if we find such module on ejabberd, let's definitely look into what we can do.

**Comment by nordurljosahvida** [comment]
@yegortimoshenko closing for now, feel free to reopen! Thanks again.
