### ISSUE TITLE
Failure to install

### ISSUE THREAD

**Issue by philhoefer** [openspace42/aenigma#36]
I'm trying to install aenigma on a fresh debian 9 installation.
On first run, the installation failed because rsync was missing.
After installing rsync, it now fails with:
```
Now that you know how XMPP works, let's get your brand new aenigma server up and running!

At least one message of any type must specified for function | dna-echo |.

Exiting...

The installation has encountered an error.

Please inspect the any error messages above and try performing the installation again or open an issue. Thank you.

Exiting...
```

**Comment by nordurljosahvida** [comment]
Can you edit aenigma/install and add "set -x" to the second line, run the installer again with "bash aenigma/setup -pl" and post the full output?

Thanks

**Comment by philhoefer** [comment]
Thanks for the quick answer.
The relevant part seems to be:
```
+ sleep 2
+ clear
+ '[' y = n ']'
+ dna-check_distro_ubuntu_18
+ grep 'Ubuntu 18.04'
+ cut -f2
+ lsb_release -d
+ false
+ dna-check_distro_debian_9
+ grep 'Debian GNU/Linux 9'
+ cut -f2
+ lsb_release -d
+ dna-abort_on_sslh_session
++ wc -l
++ grep ::1
++ grep SSH
++ printenv
+ print_env=0
+ '[' '!' 0 = 0 ']'
+ current_session_type=other
+ '[' other = sslh ']'
+ unset print_env current_session_type
+ dna-inception -h -m -p
+ '[' -f /root/openspace42/conf/inception_run_ok ']'
+ getopts :h arguments
+ case $arguments in
+ skip_hostname=y
+ getopts :h arguments
+ case $arguments in
+ dna-echo -e 'Invalid option | -m | for function | dna-inception |.'
+ '[' 2 -eq 0 ']'
+ getopts :m:s:e:n arguments
+ OPTIND=1
+ '[' -z '' ']'
+ '[' 2 -gt 2 ']'
+ '[' -z '' ']'
+ '[' -z '' ']'
+ '[' -z '' ']'
+ echo 'At least one message of any type must specified for function | dna-echo |.'
At least one message of any type must specified for function | dna-echo |.
+ echo

+ echo 'Exiting...'
Exiting...
+ echo

+ sleep 1
+ exit
The installation has encountered an error.

Please inspect the any error messages above and try performing the installation again or open an issue. Thank you.

Exiting...
```
Is that sufficient or do you need the earlier parts too?

**Comment by philhoefer** [comment]
Also, it seems running "bash aenigma/setup -pl" reverts the addition of "set -x" to aenigma/install.

**Comment by nordurljosahvida** [comment]
Can you please:

`cat openspace42/dna/version_installed`
`cat openspace42/aenigma/conf/version/*`

Thanks

**Comment by nordurljosahvida** [comment]
@philhoefer I've fixed the rsync issue btw, I thought I had encountered the same error on debian but later couldn't reproduce it and therefore thought it was an erroneous impression of mine that it didn't have rsync installed by default, but apparently it was true.

**Comment by nordurljosahvida** [comment]
I also bumped the version of our functions framework **dna** to v0.3.4, which for some reason had slipped my mind. I think that should also fix the issue you were having. Theoretically `-p l` should only always use the locally modified version and never re-clone, but since it's a rather recent feature, maybe the old version of dna at some point down your workflow broke that behaviour.

**Comment by philhoefer** [comment]
The displayed versions were v0.3.3 for dna and v0.6.3 for aenigma.
I retried installation with the new dna version just now and it works.
Thanks for the help, I'll open a new issue if I have any more problems.

**Comment by nordurljosahvida** [comment]
Awesome thanks!

**Comment by nordurljosahvida** [comment]
If you like the project, join us at os@xc.os.vu for openspace hackerspace in MIlano and aenigma@xc.os.vu for aenigma! And star the github repo if you'd like ;]
