### ISSUE TITLE
[SOLVED] Failed to start ejabberd

### ISSUE THREAD

**Issue by rowie** [openspace42/aenigma#48]
Hi,

after running your awesome script ejabberd doesn´t came up. :-(

`root@ae01:~# service ejabberd status
● ejabberd.service - A distributed, fault-tolerant Jabber/XMPP server
   Loaded: loaded (/lib/systemd/system/ejabberd.service; enabled; vendor preset: enabled)
   Active: activating (start) since Fri 2019-03-01 13:19:15 CET; 1min 0s ago
     Docs: https://www.process-one.net/en/ejabberd/docs/
Cntrl PID: 3682 (sh)
    Tasks: 3 (limit: 4915)
   CGroup: /system.slice/ejabberd.service
           ├─3682 /bin/sh -c /usr/sbin/ejabberdctl start && /usr/sbin/ejabberdctl started
           ├─3722 /bin/sh /usr/sbin/ejabberdctl started
           └─4495 sleep 2

Mar 01 13:19:15 ae01.rowie.at systemd[1]: Starting A distributed, fault-tolerant Jabber/XMPP server...
root@ae01:~# service ejabberd status
● ejabberd.service - A distributed, fault-tolerant Jabber/XMPP server
   Loaded: loaded (/lib/systemd/system/ejabberd.service; enabled; vendor preset: enabled)
   Active: activating (auto-restart) (Result: exit-code) since Fri 2019-03-01 13:20:22 CET; 4s ago
     Docs: https://www.process-one.net/en/ejabberd/docs/
  Process: 3682 ExecStart=/bin/sh -c /usr/sbin/ejabberdctl start && /usr/sbin/ejabberdctl started (code=exited, status=1/FAILURE)

Mar 01 13:20:22 ae01.rowie.at systemd[1]: ejabberd.service: Control process exited, code=exited status=1
Mar 01 13:20:22 ae01.rowie.at systemd[1]: Failed to start A distributed, fault-tolerant Jabber/XMPP server.
Mar 01 13:20:22 ae01.rowie.at systemd[1]: ejabberd.service: Unit entered failed state.
Mar 01 13:20:22 ae01.rowie.at systemd[1]: ejabberd.service: Failed with result 'exit-code'.` 

What can i do to help you troubleshooting the problem?

**Comment by rowie** [comment]
when i look at journalctl -xef i see this:

`-- Unit ejabberd.service has begun starting up.
Mar 01 13:23:58 ae01.rowie.at sh[6413]: Protocol 'inet_tcp': register/listen error: Protocol 'inet_tcp': register/listen error: Protocol 'inet_tcp': register/listen error: Protocol 'inet_tcp': register/listen error: Protocol 'inet_tcp': register/listen error: Protocol 'inet_tcp': register/listen error: Protocol 'inet_tcp': register/listen error: Protocol 'inet_tcp': register/listen error: Protocol 'inet_tcp': register/listen error: Protocol 'inet_tcp': register/listen error: Protocol 'inet_tcp': register/listen error: Protocol 'inet_tcp': register/listen error: Protocol 'inet_tcp': register/listen error: Protocol 'inet_tcp': register/listen error: Protocol 'inet_tcp': register/listen error: Protocol 'inet_tcp': register/listen error: Protocol 'inet_tcp': register/listen error: Protocol 'inet_tcp': register/listen error: Protocol 'inet_tcp': register/listen error: Protocol 'inet_tcp': register/listen error: Protocol 'inet_tcp': register/listen error: Protocol 'inet_tcp': register/listen error: Protocol 'inet_tcp': register/listen error: Protocol 'inet_tcp': register/listen error: Protocol 'inet_tcp': register/listen error: Protocol 'inet_tcp': register/listen error: Protocol 'inet_tcp': register/listen error: Protocol 'inet_tcp': register/listen error: Protocol 'inet_tcp': register/listen error:
Mar 01 13:23:58 ae01.rowie.at systemd[1]: ejabberd.service: Control process exited, code=exited status=1
Mar 01 13:23:58 ae01.rowie.at systemd[1]: Failed to start A distributed, fault-tolerant Jabber/XMPP server.
-- Subject: Unit ejabberd.service has failed
-- Defined-By: systemd
-- Support: https://www.debian.org/support
--
-- Unit ejabberd.service has failed.
--
-- The result is failed.
Mar 01 13:23:58 ae01.rowie.at systemd[1]: ejabberd.service: Unit entered failed state.
Mar 01 13:23:58 ae01.rowie.at systemd[1]: ejabberd.service: Failed with result 'exit-code'.
Mar 01 13:24:03 ae01.rowie.at systemd[1]: ejabberd.service: Service hold-off time over, scheduling restart.
Mar 01 13:24:03 ae01.rowie.at systemd[1]: Stopped A distributed, fault-tolerant Jabber/XMPP server.
-- Subject: Unit ejabberd.service has finished shutting down
-- Defined-By: systemd
-- Support: https://www.debian.org/support
--
-- Unit ejabberd.service has finished shutting down.`

always repeating 


``

**Comment by nordurljosahvida** [comment]
Hi there!

```
lsb_release -a
cat /var/log/ejabberd/error.org
```

and post the output here please

**Comment by rowie** [comment]
root@ae01:~# lsb_release -a
No LSB modules are available.
Distributor ID: Debian
Description:    Debian GNU/Linux 9.8 (stretch)
Release:        9.8
Codename:       stretch


root@ae01:~# cat /var/log/ejabberd/error.org
cat: /var/log/ejabberd/error.org: No such file or directory


i only have a /var/log/ejabberd/www_access.log
should i touch a error.log?

**Comment by rowie** [comment]
any news? :-)

**Comment by nordurljosahvida** [comment]
Hi! I had replied to you on the xmpp group only. Please re-run the 
installer and post the entire output here.

**Comment by rowie** [comment]
The problem only affects installation behind NAT!!

**Comment by Bernd84** [comment]
hi, i have the same problem,

Job for ejabberd.service failed because the control process exited with error code.
See "systemctl status ejabberd.service" and "journalctl -xe" for details.
root@ae01:~# 

what do you mean with nat?
i'm not a developer...

i have a xigmanas with virtualbox and ubuntu 18.04 installed

virtualbox option is network bridge

domain from namecheap with "DynamicDNS ip4"

**Comment by rowie** [comment]
hi bernd84,

you need a public ip cause its build to run on public servers without Network Address Translation between. ;-)
A small and cheap VPS is the best way.
Or a Routed ISP at home without NAT.
Hope this helps you!

br,
rowie

**Comment by nordurljosahvida** [comment]
@Bernd84 sorry for the late reply have you solved this issue? As @rowie said you need a public IPv4 address to run aenigma, if you're not sure what this means or you need any help, simply send me an email with how to log in to your machine and I'll gladly take a look!

**Comment by nordurljosahvida** [comment]
closing for now

**Comment by Vladimir7i** [comment]
where is solution? I have the same problem all the time(restart vps is help, but I don't want restart it all the time)
