### ISSUE TITLE
certificate renewal fails

### ISSUE THREAD

**Issue by noerw** [openspace42/aenigma#54]
It seems like the selected `manual` method of certbot does not allow for automated certificate renewal.
Or is something wrong with my setup and this method shouldn't be selected in the first place?

**Comment by nordurljosahvida** [comment]
have you upgraded to the latest version? [0.6.14?] if not `aenigma-upgrade` as root.

**Comment by noerw** [comment]
yes, i did. The content of `/etc/letsencrypt/renew/my.domain.conf` looks still like this:

```
# renew_before_expiry = 30 days
version = 0.28.0
archive_dir = /etc/letsencrypt/archive/my.domain
cert = /etc/letsencrypt/live/my.domain/cert.pem
privkey = /etc/letsencrypt/live/my.domain/privkey.pem
chain = /etc/letsencrypt/live/my.domain/chain.pem
fullchain = /etc/letsencrypt/live/my.domain/fullchain.pem

# Options used in the renewal process
[renewalparams]
account = **************************************************
server = https://acme-v02.api.letsencrypt.org/directory
manual_public_ip_logging_ok = True
authenticator = manual
pref_challs = dns-01,
```

**edit**: I'm starting to believe that #55 is the root cause for this

**Comment by nordurljosahvida** [comment]
Ok let's fix #55 first then

**Comment by nordurljosahvida** [comment]
@noerw waiting for your feedback on #55 thanks again

**Comment by nordurljosahvida** [comment]
@noerw any news on this?

**Comment by noerw** [comment]
I can't test this atm, as a cert renewal is now due in 58 days.
However my certbot configuration still remains as described in 'manual' mode after rerunning `aenigma-upgrade` (see https://github.com/openspace42/aenigma/issues/54#issuecomment-483747650), so I don't see this issue as resolved.

I'm wondering, should certbot run the domain in manual verification in the first place? Or was this configuration created in error due to https://github.com/openspace42/aenigma/issues/55#issuecomment-483758505 ?

**Comment by nordurljosahvida** [comment]
Just checked, yes manual is correct, this is my configuration:

```
# renew_before_expiry = 30 days
version = 0.28.0
archive_dir = /etc/letsencrypt/archive/my.domain
cert = /etc/letsencrypt/live/my.domain/cert.pem
privkey = /etc/letsencrypt/live/my.domain/privkey.pem
chain = /etc/letsencrypt/live/my.domain/chain.pem
fullchain = /etc/letsencrypt/live/my.domain/fullchain.pem

# Options used in the renewal process
[renewalparams]
account = **************************************************
pref_challs = dns-01,
server = https://acme-v02.api.letsencrypt.org/directory
authenticator = manual
manual_public_ip_logging_ok = True
```

aenigma will automatically check to renew certs every second day of the month
