### ISSUE TITLE
Disable all logging by default

### ISSUE THREAD

**Issue by nordurljosahvida** [openspace42/aenigma#60]

**Comment by solus-hq** [comment]
@nordurljosahvida Hello! This is a great enhancement for privacy focused users. It would be as well great to ask users during the installation process if they want to store archived messages on the server or not.

**Comment by solus-hq** [comment]
@nordurljosahvida  Do you mean having all logging disabled on the server or just ejabberd logging? Keeping everything private would be an option for privacy conscious users.

**Comment by nordurljosahvida** [comment]
I would apply it to everything, like they do in streisand, so that a seized server would have no [or as little as possible] personally identifiable information thereby guaranteeing deniability

**Comment by nordurljosahvida** [comment]
Let's move this one to: https://github.com/openspace42/aenigma/issues/61
