### ISSUE TITLE
Ask users if they want to store message archives on the server (installer)

### ISSUE THREAD

**Issue by solus-hq** [openspace42/aenigma#61]
It would be nice to have this option when installing aenigma on a fresh machine.

**Comment by nordurljosahvida** [comment]
You're talking about mod_mam right?

**Comment by solus-hq** [comment]
@nordurljosahvida Yes, that's correct!

**Comment by nordurljosahvida** [comment]
Good point, this will need to be pushed to the entire cluster, will take some time to implement

**Comment by nordurljosahvida** [comment]
implemented in latest beta. let me know if that satisfies this 100%.

**Comment by solus-hq** [comment]
> implemented in latest beta. let me know if that satisfies this 100%.

I might have missed something during recent update, will the `aenigma-upgrade -db -pb` script ask us if we want to turn off mod_mam completely? It would be advisable to clear old archives as well for all users and chatrooms.

**Comment by nordurljosahvida** [comment]
still to implement that, good point, will do that today

**Comment by nordurljosahvida** [comment]
@solus-hq implemented, let me know if it works for you, thanks

**Comment by solus-hq** [comment]
@nordurljosahvida It works and Conversations compliance tester is stating that MAM is disabled.

**Comment by nordurljosahvida** [comment]
Awesome thanks!
