### ISSUE TITLE
Installer bug: "unbound variable"

### ISSUE THREAD

**Issue by solus-hq** [openspace42/aenigma#62]
Below is the installer output on a fresh 18.04 machine, issue arises when I accidentally input a cyrillic letter.
 
```
Also ensure you're applying the correct setting to the authoritative DNS provider for this zone.

Perform checks for this DNS record once again from the beginning? (Y[es]/s[kip this check]/e[xit all checks]) н

Invalid option. Try again...

/root/openspace42/dna/functions/check_dns_record: line 298: message: unbound variable
```

**Comment by nordurljosahvida** [comment]
Yeah it's a known issue that in some cases this error occurs when strange input is entered, didn't know about cyrillic letters. Thanks

**Comment by nordurljosahvida** [comment]
I'll take a look

**Comment by nordurljosahvida** [comment]
should be fixed, please try again with `bash aenigma/setup -db -pb`
