### ISSUE TITLE
Ubuntu 18.04: cp: cannot create regular file '/etc/letsencrypt/renewal-hooks/post/aenigma-create-push-certs': No such file or directory

### ISSUE THREAD

**Issue by solus-hq** [openspace42/aenigma#63]
Receiving an error right after successfully passing DNS checks: 

`cp: cannot create regular file '/etc/letsencrypt/renewal-hooks/post/aenigma-create-push-certs': No such file or directory`

**Comment by nordurljosahvida** [comment]
I'll check in about 20 minutes

**Comment by solus-hq** [comment]
I could bypass this by running `bash openspace42/aenigma/tools/aenigma-create-push-certs` separately and then re-running main install script

**Comment by nordurljosahvida** [comment]
Good to know, was the first one a fresh install?

**Comment by solus-hq** [comment]
Yes, the first one was on a fresh install, I tried running main install script 2 times.

**Comment by nordurljosahvida** [comment]
ok

**Comment by nordurljosahvida** [comment]
should be fixed, if you still haven't finished setting up and would like to help test, simply:

```
apt purge certbot
rm -rf /etc/letsencrypt/
bash aenigma/setup -db -pb
```

Thanks

**Comment by solus-hq** [comment]
I've encountered this issue once again when doing a clean install, it shows up if DNS checks fail and I choose to `(e)xit all checks`

Once again, it can be fixed by running `bash openspace42/aenigma/tools/aenigma-create-push-certs` separately once DNS propagation is complete.

**Comment by nordurljosahvida** [comment]
@solus-hq were you performing this clean install with "-db -pb"? Because this should be fixed in bleeding edge.

**Comment by solus-hq** [comment]
> @solus-hq were you performing this clean install with "-db -pb"? Because this should be fixed in bleeding edge.

Ooops, no, I was using stable version.

**Comment by nordurljosahvida** [comment]
ok, good, i'm glad ;]
