### ISSUE TITLE
Creating a new account using TOR hidden service address fails

### ISSUE THREAD

**Issue by solus-hq** [openspace42/aenigma#64]
Setup:

* tor running as service, port 9050 opened
* tested with gajim, psi+, pidgin

To reproduce: 

I was trying to follow the steps from this manual:

https://creep.im/xmpp_tor/

1. Try creating a new account and specify aenigma instance TOR hidden service address as XMPP server address
2. Specify TOR localhost proxy as SOCKS5 proxy to connect to the server

Every client fails, connection fails.

<img width="468" alt="Screen Shot 2019-05-08 at 20 16 15" src="https://user-images.githubusercontent.com/26515805/57395936-ebd1a780-71d1-11e9-82b5-d314314acef8.png">

<img width="532" alt="Screen Shot 2019-05-08 at 20 16 32" src="https://user-images.githubusercontent.com/26515805/57395950-f429e280-71d1-11e9-942a-7bf9d90fc6e2.png">

**Comment by nordurljosahvida** [comment]
@solus-hq this should have been fixed back when I added .onion domain to ejabberd. Let's finish installing your server and re-open if needed.
