### ISSUE TITLE
TOR: create new xmpp id, .onion <-> .onion routing, converse.js issues

### ISSUE THREAD

**Issue by solus-hq** [openspace42/aenigma#68]
We can't create a new account and fetch registration form via self-hosted Converse.js instance

<img width="1106" alt="Screen Shot 2019-05-19 at 22 27 09" src="https://user-images.githubusercontent.com/26515805/57996977-0f022e00-7ad3-11e9-89b0-4bb5205e6422.png">

**Comment by nordurljosahvida** [comment]
Interesting, haven't tried using converse over Tor yet. Are you trying to register an @your-clearnet-domain.tld account or a @your-onion-hostname.onion?

**Comment by solus-hq** [comment]
> Interesting, haven't tried using converse over Tor yet. Are you trying to register an @your-clearnet-domain.tld account or a @your-onion-hostname.onion?

I'm trying to register via @my-onion-hostname.onion, sure. Just wanted to try a completely .onion solution

**Comment by nordurljosahvida** [comment]
cool, let me look into that. Try completing the upgrade first, and if you could please confirm to me that "/etc/ejabberd/ejabberd.yml" contains your .onion hostname in the top part of the config.

**Comment by solus-hq** [comment]
```
hosts:
  - "riot.nz"

loglevel: 4
log_rotate_size: 10485760
log_rotate_date: ""
log_rotate_count: 1
log_rate_limit: 100

```

**Comment by nordurljosahvida** [comment]
I think there was a general registrations issue on converse, I figured out how to use websocket instead of bosh, now it's 10x as fast, and registrations work, even for .onion domains.

**Comment by nordurljosahvida** [comment]
@solus-hq let's get your upgrade complete and then you'll see your .onion domain will show up under ejabberd hosts

**Comment by solus-hq** [comment]
@nordurljosahvida can't test it after recent upgrade because .onion/xmpp won't open at all

<img width="1145" alt="Screen Shot 2019-05-21 at 15 00 21" src="https://user-images.githubusercontent.com/26515805/58095728-53c5bc00-7bdc-11e9-9e5d-ef0f3b65cb01.png">

**Comment by nordurljosahvida** [comment]
@solus-hq works for me, try again now.

Also, I've made a small change to your converse so that it'll use websocket to ejabberd over tor, also to hide your domain, how cool is that? I'll implement this later today for everyone.

**Comment by solus-hq** [comment]
> @solus-hq works for me, try again now.
> 
> Also, I've made a small change to your converse so that it'll use websocket to ejabberd over tor, also to hide your domain, how cool is that? I'll implement this later today for everyone.

That's really cool!

**Comment by solus-hq** [comment]
@nordurljosahvida But still, I can't seem to be able to create a new account via Converse.js, 

1. Converse won't fetch registration form if I provide my .onion domain as a server to create an account with. 
2. When I try to create a new account via Pidgin / Gajim, it won't fetch registration form as well.
3. Having created a new .onion user manually via ejabberd admin I can't login via Converse as it's displaying the following error: 

> Connection failure
> The WebSocket connection could not be established or was disconnected.

**Comment by nordurljosahvida** [comment]
1, 3] are you trying from tor browser or from clearnet? Because I configured your converse.js to work only via tor for now, i'm working on splitting the two instances to make it work separately for clearnet and tor. It does work via tor browser right now for me.

2] are they connecting over tor or clearnet?

**Comment by solus-hq** [comment]
Everything is done via Tor Browser. 

To sum up: 

1. I **can** access ejabberd admin via .onion domain in Tor Browser ✅
2. I **can** create a new .onion xmpp id in ejabberd admin ✅
3. I **can** login using an .onion xmpp id via pidgin, gajim, adium ✅
4. I **can't** create a new xmpp id in .onion domain via pidgin, gajim, adium ❌
5. I **can't** login via Converse in .onion domain via Tor Browser ❌
6. I **can't** create a new xmpp id in .onion domain via Tor Browser using Converse since it fails some websocket connection. ❌

**Comment by nordurljosahvida** [comment]
@solus-hq figured this out, when including a wss:// that has an invalid certificate the user's browser doesn't accept it and the connection is not made behind the scenes. Either the user manually visits the wss:// address changing it with https:// and accepts the invalid cert locally, or we find a solution here: https://github.com/conversejs/converse.js/issues/1583

**Comment by solus-hq** [comment]
@nordurljosahvida updated the comment above

**Comment by solus-hq** [comment]
Performed some tests to see if we can chat with other .onion servers.

Setup:
* macOS
* Adium
* tor installed via brew and listening to 127.1:9050
 
Having successfully added 2 different xmpp ids from 2 different .onion service I wasn't able to send a message or start a chat between these ids. Adium is reporting an error. 

<img width="538" alt="Screen Shot 2019-05-29 at 21 03 53" src="https://user-images.githubusercontent.com/26515805/58580717-6f713800-8256-11e9-9628-06ac709bcc4e.png">

**Comment by nordurljosahvida** [comment]
@solus-hq any news?

**Comment by nordurljosahvida** [comment]
@solus-hq I think this is fixed.
