### ISSUE TITLE
/root/aenigma/functions: line 1614: updatedb: command not found 

### ISSUE THREAD

**Issue by Bernd84** [openspace42/aenigma#81]
hi, i have this error 

Now enabling ejabberd...

/root/aenigma/functions: line 1614: updatedb: command not found

**Comment by nordurljosahvida** [comment]
@Bernd84 Hi, sorry for the very late reply. Let me check.

**Comment by nordurljosahvida** [comment]
@Bernd84 fixed, you can fix locally with:

`apt install mlocate` and re-running the install.

This will be fixed in next release.

Thanks!
