### ISSUE TITLE
Installer IPv4 display issue

### ISSUE THREAD

**Issue by solus-hq** [openspace42/aenigma#83]
Every time I'm installing on a fresh machine installer asks me this question but never shows any IP address

`Is this the correct public IPv4 you'd like to use for this machine? (Y/n): y`

Then it shows the IP and asks if it's correct

`Is | 127.0.0.1 | correct? (Y/n/e[xit]) y`

I guess we don't need to ask users for excess confirmations without showing any information pertinent to question.

**Comment by nordurljosahvida** [comment]
Had noticed this, now fixed, thanks
