### ISSUE TITLE
Project status and contacts

### ISSUE THREAD

**Issue by solus-hq** [openspace42/aenigma#91]
@nordurljosahvida I was not able to contact you via your email or XMPP, are these still working?

**Comment by nordurljosahvida** [comment]
Hi! Sorry, i was going to get back to you but things have been crazy at work.

How are things?

Thank you so much for reaching out. 

I am literally right now opening the ejabberd blog to see what i've missed. The virus situation in italy is slowing everything down work-wise and we've had to temporarily close the store down until things are resolved.

So - naturally - I'm taking a look at the project, and how to get it back on track.

We're planning a major and complete server migration here at openspace very soon and I'm gathering ToDos for our framework.

CloudFlare / MailInABox / whaterver else DNS API integration is very soon on the list, and most importantly finishing the last few logic and implementation steps for backup/restore are the key points holding back the next release.

The project definitely needs some people and - possibly - influx of cash for them [i'm not looking to get any of it until the project grows out one day hopefully] on a tip-for-commit basis.

We also have exciting projects coming up with our friends over at Parrot security os [a very large and successful project actually] and aenigma will be a part of this new joint project of ours very soon.

Thank you so much for still believing in this and sorry I've had to sign off for so long, but the store has been draining my soul [in a very good way though] and projects we were hoping to finish by december are still ongoing [italians ;] so until those are completed we'll be remaining in this lockdown mode of sorts, hopefully going positive by end of year.

If this virus situation goes on - as it's now starting to seem - until the end of the month or even the beginning of april, i'll have some time to dedicate to all of this.

I also feel in debt to our Patron supporters [one of whom has - more than understandibly - just left the project] and will make it right very soon to all of them.

Thank to all who are still here, I'm looking forward to your feedback!

Talk soon!

Nicolas
