### ISSUE TITLE
I assume the project is abandoned now

### ISSUE THREAD

**Issue by solus-hq** [openspace42/aenigma#97]
@nordurljosahvida I wasn't able to contact you via email thus I'm doing it here and would like to inquire if the project is frozen and not planned to be updated any time soon?

**Comment by nordurljosahvida** [comment]
Hi @solus-hq ! Yes the project is shutdown, please see shutdown notice on homepage. The future is exciting, look around to the projects linked on the message, and thank you so much for your support in the past. It's been a super cool ride!
